/**
 * High-Fidelity Mock Seed Data
 * Mirrored from prototype/mockData.js
 */

export const INITIAL_BDM_USER = {
  id: 'u-02',
  employee_id: 'CKR-BDM-001',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@ckrtechnologies.in',
  phone: '+91 98765 43210',
  role: 'bdm',
  designation: 'Business Development Manager',
  department: 'Sales & Telecalling',
  is_active: true,
  force_password_reset: false,
  has_seen_onboarding: true,
};

export const INITIAL_TAGS = [
  { id: 'tag-01', name: 'School Management ERP', type: 'product', is_active: true },
  { id: 'tag-02', name: 'Custom App / Website Development', type: 'service', is_active: true },
  { id: 'tag-03', name: 'Other ERP / CRM Software', type: 'product', is_active: true },
];

export const INITIAL_LEADS = [
  {
    id: 'lead-101',
    name: 'Dr. Rajeshwar Rao',
    company_name: 'Heritage Valley International School',
    account_id: 'acc-01',
    phone: '+91 98480 12345',
    email: 'principal@heritagevalley.edu.in',
    city: 'Hyderabad',
    state: 'Telangana',
    source: 'website',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'proposal',
    priority: 'high',
    budget: 450000,
    expected_value: 480000,
    probability_override: 75,
    won_amount: null,
    next_followup_date: '2026-09-22',
    last_followup_date: '2026-09-22',
    followup_count: 3,
    brd_url: '/files/brd/HeritageValley_ERP_BRD_v2.pdf',
    sub_requirement: 'Full campus automation with student fee gateway, RFID transport, and teacher grading portal for 2,400 students.',
    created_at: '2026-09-12T10:15:00Z',
    updated_at: '2026-09-22T09:40:00Z',
  },
  {
    id: 'lead-102',
    name: 'Sister Mary Joseph',
    company_name: "St. Jude's Girls Senior Secondary",
    account_id: 'acc-02',
    phone: '+91 94401 56789',
    email: 'admin@stjudeschool.ac.in',
    city: 'Secunderabad',
    state: 'Telangana',
    source: 'cold_call',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'follow_up',
    priority: 'high',
    budget: 320000,
    expected_value: 350000,
    probability_override: 50,
    won_amount: null,
    next_followup_date: '2026-09-20', // Overdue
    last_followup_date: '2026-09-18',
    followup_count: 2,
    brd_url: null,
    sub_requirement: 'Replace legacy Excel fee tracking with automated SMS alerts and biometric staff punch integration.',
    created_at: '2026-09-14T11:30:00Z',
    updated_at: '2026-09-18T16:00:00Z',
  },
  {
    id: 'lead-103',
    name: 'Mr. Vikram Singhania',
    company_name: 'Delhi Public Academy',
    account_id: 'acc-03',
    phone: '+91 98110 34567',
    email: 'vikram.singhania@dpa.edu.in',
    city: 'New Delhi',
    state: 'Delhi',
    source: 'referral',
    tag_id: 'tag-02',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'new', // Untouched!
    priority: 'high',
    budget: 400000,
    expected_value: 400000,
    probability_override: 10,
    won_amount: null,
    next_followup_date: '2026-09-22',
    last_followup_date: null,
    followup_count: 0,
    brd_url: null,
    sub_requirement: 'New iOS/Android admission app for parents with integrated Razorpay fee payment module.',
    created_at: '2026-09-22T08:00:00Z',
    updated_at: '2026-09-22T08:00:00Z',
  },
  {
    id: 'lead-104',
    name: 'Mr. Arvind Gupta',
    company_name: 'Gupta Medical & Logistics',
    account_id: 'acc-04',
    phone: '+91 98290 87654',
    email: 'arvind@guptamed.com',
    city: 'Jaipur',
    state: 'Rajasthan',
    source: 'website',
    tag_id: 'tag-03',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'new', // Untouched!
    priority: 'medium',
    budget: 380000,
    expected_value: 400000,
    probability_override: 10,
    won_amount: null,
    next_followup_date: '2026-09-23',
    last_followup_date: null,
    followup_count: 0,
    brd_url: null,
    sub_requirement: 'Warehouse inventory barcode scanning mobile app for 12 distribution hubs.',
    created_at: '2026-09-22T08:30:00Z',
    updated_at: '2026-09-22T08:30:00Z',
  },
  {
    id: 'lead-105',
    name: 'Mrs. Sunita Deshmukh',
    company_name: 'Pune Scholars World School',
    account_id: 'acc-05',
    phone: '+91 98220 99887',
    email: 'sunita@punescholars.org',
    city: 'Pune',
    state: 'Maharashtra',
    source: 'website',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'contacted',
    priority: 'medium',
    budget: 250000,
    expected_value: 260000,
    probability_override: 25,
    won_amount: null,
    next_followup_date: '2026-09-24',
    last_followup_date: '2026-09-21',
    followup_count: 1,
    brd_url: null,
    sub_requirement: 'Interested in School ERP fee management and online examination module.',
    created_at: '2026-09-18T14:10:00Z',
    updated_at: '2026-09-21T11:00:00Z',
  },
  {
    id: 'lead-106',
    name: 'Col. K. S. Rathore (Retd.)',
    company_name: 'Apex National Academy',
    account_id: 'acc-06',
    phone: '+91 94140 11223',
    email: 'director@apexnational.edu.in',
    city: 'Kota',
    state: 'Rajasthan',
    source: 'cold_call',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'proposal',
    priority: 'high',
    budget: 520000,
    expected_value: 550000,
    probability_override: 60,
    won_amount: null,
    next_followup_date: '2026-09-25',
    last_followup_date: '2026-09-20',
    followup_count: 4,
    brd_url: '/files/brd/Apex_National_Academy_ERP_Proposal.pdf',
    sub_requirement: 'Hostel warden mess billing and biometric turnstile integration for 1,800 students.',
    created_at: '2026-09-08T09:00:00Z',
    updated_at: '2026-09-20T17:30:00Z',
  },
  {
    id: 'lead-107',
    name: 'Fr. Thomas Kizhakkethil',
    company_name: 'Don Bosco Higher Secondary',
    account_id: 'acc-07',
    phone: '+91 94471 22334',
    email: 'principal@donboscokerala.in',
    city: 'Kochi',
    state: 'Kerala',
    source: 'referral',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'won',
    priority: 'high',
    budget: 450000,
    expected_value: 450000,
    probability_override: 100,
    won_amount: 450000,
    next_followup_date: null,
    last_followup_date: '2026-09-19',
    followup_count: 5,
    brd_url: '/files/brd/DonBosco_Kochi_Signed_Agreement.pdf',
    sub_requirement: 'Multi-lingual fee portal in English and Malayalam with automatic receipt generator.',
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-19T15:20:00Z',
  },
  {
    id: 'lead-110',
    name: 'Mrs. Gayatri Nambiar',
    company_name: 'Bhavans Vidya Mandir',
    account_id: 'acc-08',
    phone: '+91 98499 66554',
    email: 'gayatri.nambiar@bhavans.org',
    city: 'Bengaluru',
    state: 'Karnataka',
    source: 'website',
    tag_id: 'tag-01',
    deal_type: 'new_business',
    assigned_to: 'u-02',
    status: 'follow_up',
    priority: 'medium',
    budget: 300000,
    expected_value: 320000,
    probability_override: 40,
    won_amount: null,
    next_followup_date: '2026-09-22', // Due Today
    last_followup_date: '2026-09-19',
    followup_count: 2,
    brd_url: null,
    sub_requirement: 'Evaluate demo on bus GPS tracking and automated parent notifications.',
    created_at: '2026-09-15T12:00:00Z',
    updated_at: '2026-09-19T14:00:00Z',
  },
];

export const INITIAL_INTERACTIONS = [
  {
    id: 'int-201',
    lead_id: 'lead-101',
    bdm_id: 'u-02',
    type: 'call',
    call_result_type: 'positive',
    call_result_label: 'Terms Agreed / Deal Finalizing',
    notes: 'Reviewed revised commercial proposal with Dr. Rao. Management board approved ₹4.8L quote. Awaiting signed PO copy by Friday.',
    status_snapshot: 'proposal',
    next_action: 'Collect signed agreement & advance cheque',
    created_at: '2026-09-22T11:15:00Z',
  },
  {
    id: 'int-202',
    lead_id: 'lead-102',
    bdm_id: 'u-02',
    type: 'call',
    call_result_type: 'neutral',
    call_result_label: 'Ringing / No Answer',
    notes: 'Attempted morning follow-up call. Phone rang with no answer. Sent reminder WhatsApp on fee portal demo.',
    status_snapshot: 'follow_up',
    next_action: 'Retry telephone call at 3:30 PM',
    created_at: '2026-09-22T10:45:00Z',
  },
  {
    id: 'int-203',
    lead_id: 'lead-106',
    bdm_id: 'u-02',
    type: 'meeting',
    call_result_type: 'positive',
    call_result_label: 'Virtual Demo Completed',
    notes: 'Conducted 45-minute live screen demo of hostel mess inventory & student turnstile attendance module with Col. Rathore.',
    status_snapshot: 'proposal',
    next_action: 'Share tailored commercial estimate for 1,800 students',
    created_at: '2026-09-22T10:00:00Z',
  },
  {
    id: 'int-204',
    lead_id: 'lead-101',
    bdm_id: 'u-02',
    type: 'call',
    call_result_type: 'positive',
    call_result_label: 'Positive / Next Step Set',
    notes: 'Addressed questions regarding transport GPS latency and parent Android push notifications. Clarified cloud server SLA.',
    status_snapshot: 'proposal',
    next_action: 'Issue final revision of Annexure A',
    created_at: '2026-09-21T15:20:00Z',
  },
  {
    id: 'int-205',
    lead_id: 'lead-107',
    bdm_id: 'u-02',
    type: 'site_visit',
    call_result_type: 'positive',
    call_result_label: 'Won / Agreement Signed',
    notes: 'In-person campus visit to Don Bosco Kochi. Handed over physical ERP licence agreement signed by Fr. Thomas. First tranche ₹2.25L NEFT confirmed.',
    status_snapshot: 'won',
    next_action: 'Onboarding handover to tech implementation team',
    created_at: '2026-09-19T14:30:00Z',
  },
];

export const INITIAL_ATTENDANCE = [
  {
    id: 'att-301',
    bdm_id: 'u-02',
    date: '2026-09-22',
    check_in_time: '2026-09-22T09:28:00Z',
    check_out_time: null,
    status: 'present',
  },
  {
    id: 'att-302',
    bdm_id: 'u-02',
    date: '2026-09-21',
    check_in_time: '2026-09-21T09:30:00Z',
    check_out_time: '2026-09-21T18:45:00Z',
    status: 'present',
  },
  {
    id: 'att-303',
    bdm_id: 'u-02',
    date: '2026-09-20',
    check_in_time: null,
    check_out_time: null,
    status: 'holiday', // Sunday
  },
  {
    id: 'att-304',
    bdm_id: 'u-02',
    date: '2026-09-19',
    check_in_time: '2026-09-19T09:25:00Z',
    check_out_time: '2026-09-19T18:30:00Z',
    status: 'present',
  },
  {
    id: 'att-305',
    bdm_id: 'u-02',
    date: '2026-09-18',
    check_in_time: '2026-09-18T09:32:00Z',
    check_out_time: '2026-09-18T18:40:00Z',
    status: 'present',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-401',
    user_id: 'u-02',
    lead_id: 'lead-102',
    type: 'followup_overdue',
    message: "Overdue callback: Sister Mary Joseph (St. Jude's Girls) was scheduled for 20 Sep 2026.",
    is_read: false,
    created_at: '2026-09-22T09:00:00Z',
  },
  {
    id: 'notif-402',
    user_id: 'u-02',
    lead_id: 'lead-103',
    type: 'lead_assigned',
    message: 'New high-priority lead assigned: Delhi Public Academy (Mr. Vikram Singhania).',
    is_read: false,
    created_at: '2026-09-22T08:05:00Z',
  },
  {
    id: 'notif-403',
    user_id: 'u-02',
    lead_id: 'lead-104',
    type: 'lead_assigned',
    message: 'New lead assigned from website: Gupta Medical & Logistics (Mr. Arvind Gupta).',
    is_read: true,
    created_at: '2026-09-22T08:35:00Z',
  },
];
