// Realistic mock data for CKR Internal CRM Prototype
const MOCK_DATA = {
  users: [
    {
      id: "u-01",
      employee_id: "CKR-ADM-001",
      name: "Chandan Mallik",
      email: "chandan@ckrtechnologies.in",
      phone: "+91 98765 43210",
      role: "admin",
      designation: "Co-Founder & CTO",
      department: "Leadership",
      date_of_joining: "2023-01-15",
      status: "active",
      is_active: true,
      force_password_reset: false,
      has_seen_onboarding: true
    },
    {
      id: "u-02",
      employee_id: "CKR-BDM-001",
      name: "Aarav Sharma",
      email: "aarav.sharma@ckrtechnologies.in",
      phone: "+91 98112 34567",
      role: "bdm",
      designation: "Senior BDM",
      department: "Sales",
      date_of_joining: "2025-06-10",
      status: "active",
      is_active: true,
      force_password_reset: false,
      has_seen_onboarding: true
    },
    {
      id: "u-03",
      employee_id: "CKR-BDM-002",
      name: "Priya Patel",
      email: "priya.patel@ckrtechnologies.in",
      phone: "+91 97234 56789",
      role: "bdm",
      designation: "BDM - Education ERP",
      department: "Sales",
      date_of_joining: "2025-08-01",
      status: "active",
      is_active: true,
      force_password_reset: false,
      has_seen_onboarding: true
    },
    {
      id: "u-04",
      employee_id: "CKR-BDM-003",
      name: "Rohan Verma",
      email: "rohan.verma@ckrtechnologies.in",
      phone: "+91 96543 21098",
      role: "bdm",
      designation: "BDM - Custom Dev",
      department: "Sales",
      date_of_joining: "2025-11-15",
      status: "active",
      is_active: true,
      force_password_reset: false,
      has_seen_onboarding: true
    },
    {
      id: "u-05",
      employee_id: "CKR-BDM-004",
      name: "Ananya Iyer",
      email: "ananya.iyer@ckrtechnologies.in",
      phone: "+91 94456 78901",
      role: "bdm",
      designation: "Associate BDM",
      department: "Sales",
      date_of_joining: "2026-03-01",
      status: "active",
      is_active: true,
      force_password_reset: true,
      has_seen_onboarding: false
    }
  ],

  tags: [
    { id: "tag-01", name: "School Management ERP", type: "product", is_active: true },
    { id: "tag-02", name: "Custom App & Web Dev", type: "service", is_active: true },
    { id: "tag-03", name: "Hospital ERP Suite", type: "product", is_active: true },
    { id: "tag-04", name: "Warehouse & Inventory ERP", type: "product", is_active: false }
  ],

  accounts: [
    {
      id: "acc-01",
      name: "Delhi Public Academy Trust",
      state: "Delhi",
      city: "New Delhi",
      created_by: "u-01",
      created_at: "2025-04-12T10:00:00Z",
      lifetime_revenue: 850000,
      won_leads_count: 2,
      total_leads_count: 3
    },
    {
      id: "acc-02",
      name: "Apex Logistics & Supply Chain Ltd",
      state: "Maharashtra",
      city: "Pune",
      created_by: "u-01",
      created_at: "2025-07-20T11:30:00Z",
      lifetime_revenue: 620000,
      won_leads_count: 1,
      total_leads_count: 2
    },
    {
      id: "acc-03",
      name: "Kaveri Hospital & Diagnostics",
      state: "Tamil Nadu",
      city: "Chennai",
      created_by: "u-01",
      created_at: "2025-10-05T09:15:00Z",
      lifetime_revenue: 480000,
      won_leads_count: 1,
      total_leads_count: 2
    },
    {
      id: "acc-04",
      name: "Heritage Valley International School",
      state: "Telangana",
      city: "Hyderabad",
      created_by: "u-01",
      created_at: "2026-01-14T14:45:00Z",
      lifetime_revenue: 0,
      won_leads_count: 0,
      total_leads_count: 1
    }
  ],

  leads: [
    {
      id: "lead-101",
      name: "Dr. Rajeshwar Rao",
      company_name: "Heritage Valley International School",
      account_id: "acc-04",
      phone: "+91 98480 12345",
      email: "director@heritagevalley.edu.in",
      city: "Hyderabad",
      state: "Telangana",
      source: "website",
      tag_id: "tag-01",
      deal_type: "new_business",
      assigned_to: "u-02",
      status: "proposal",
      priority: "high",
      budget: 500000,
      expected_value: 480000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-22", // Today!
      last_followup_date: "2026-09-18",
      followup_count: 4,
      brd_url: "/files/brd/lead-101/HeritageValley_BRD_v2.pdf",
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-02T10:15:00Z",
      sub_requirement: "1,200 students, fee management with UPI gateway, RFID student bus tracking, attendance biometric integration."
    },
    {
      id: "lead-102",
      name: "Vikram Singhania",
      company_name: "Apex Logistics & Supply Chain Ltd",
      account_id: "acc-02",
      phone: "+91 98200 45678",
      email: "vikram@apexlogistics.in",
      city: "Pune",
      state: "Maharashtra",
      source: "referral",
      tag_id: "tag-02",
      deal_type: "upsell",
      assigned_to: "u-02",
      status: "follow_up",
      priority: "high",
      budget: 350000,
      expected_value: 320000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-21", // Overdue!
      last_followup_date: "2026-09-15",
      followup_count: 3,
      brd_url: "/files/brd/lead-102/DriverMobileApp_Scope.pdf",
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-05T14:20:00Z",
      sub_requirement: "Driver dispatch React Native app for Android with GPS tracking and offline POD capture."
    },
    {
      id: "lead-103",
      name: "Sister Mary Augustine",
      company_name: "St. Jude Convent Senior Sec School",
      account_id: null,
      phone: "+91 94120 78901",
      email: "principal@stjudeagra.org",
      city: "Agra",
      state: "Uttar Pradesh",
      source: "cold_call",
      tag_id: "tag-01",
      deal_type: "new_business",
      assigned_to: "u-03",
      status: "contacted",
      priority: "medium",
      budget: 250000,
      expected_value: 240000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-24",
      last_followup_date: "2026-09-19",
      followup_count: 2,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-10T11:00:00Z",
      sub_requirement: "Report card generation as per CBSE guidelines and parent SMS notification system."
    },
    {
      id: "lead-104",
      name: "Manish Kothari",
      company_name: "Kothari Agro Commodities",
      account_id: null,
      phone: "+91 97140 23456",
      email: "manish@kothariagro.com",
      city: "Ahmedabad",
      state: "Gujarat",
      source: "social_media",
      tag_id: "tag-02",
      deal_type: "new_business",
      assigned_to: "u-04",
      status: "new",
      priority: "medium",
      budget: 400000,
      expected_value: 400000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-23",
      last_followup_date: null,
      followup_count: 0,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-21T16:45:00Z",
      sub_requirement: "B2B trading portal with mandi rate integration and GST invoice generation."
    },
    {
      id: "lead-105",
      name: "Father Thomas Mathew",
      company_name: "Delhi Public Academy Trust",
      account_id: "acc-01",
      phone: "+91 98100 99887",
      email: "thomas@dpatrust.org",
      city: "New Delhi",
      state: "Delhi",
      source: "referral",
      tag_id: "tag-01",
      deal_type: "upsell",
      assigned_to: "u-02",
      status: "won",
      priority: "high",
      budget: 450000,
      expected_value: 450000,
      probability_override: null,
      won_amount: 450000,
      next_followup_date: null,
      last_followup_date: "2026-09-14",
      followup_count: 5,
      brd_url: "/files/brd/lead-105/DPA_Phase2_Signed.pdf",
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-08-15T09:30:00Z",
      sub_requirement: "Second campus rollout (Gurugram branch) with unified multi-branch reporting."
    },
    {
      id: "lead-106",
      name: "Suresh Chandra",
      company_name: "Chandra Automotives Pvt Ltd",
      account_id: null,
      phone: "+91 99880 11223",
      email: "suresh@chandraauto.co.in",
      city: "Indore",
      state: "Madhya Pradesh",
      source: "website",
      tag_id: "tag-02",
      deal_type: "new_business",
      assigned_to: "u-04",
      status: "lost",
      priority: "low",
      budget: 180000,
      expected_value: 180000,
      probability_override: null,
      won_amount: null,
      next_followup_date: null,
      last_followup_date: "2026-09-12",
      followup_count: 3,
      brd_url: null,
      lost_reason: "Chose a local vendor offering ready-made WordPress template for ₹40,000.",
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-08-28T12:00:00Z",
      sub_requirement: "Dealer showcase website with service appointment booking."
    },
    {
      id: "lead-107",
      name: "Amitabh Sen",
      company_name: "Kolkata Retail Mart",
      account_id: null,
      phone: "+91 90000 00000",
      email: "test@nowhere.com",
      city: "Kolkata",
      state: "West Bengal",
      source: "website",
      tag_id: "tag-02",
      deal_type: "new_business",
      assigned_to: "u-03",
      status: "invalid",
      priority: "low",
      budget: null,
      expected_value: null,
      probability_override: null,
      won_amount: null,
      next_followup_date: null,
      last_followup_date: "2026-09-16",
      followup_count: 1,
      brd_url: null,
      lost_reason: null,
      invalid_reason: "wrong_number",
      created_by: "u-01",
      created_at: "2026-09-16T15:10:00Z",
      sub_requirement: "Inbound form test submission with dummy number."
    },
    {
      id: "lead-108",
      name: "Dr. Suniti Deshmukh",
      company_name: "Deshmukh Multi-Speciality Clinic",
      account_id: null,
      phone: "+91 98230 65432",
      email: "dr.deshmukh@deshmukhclinic.in",
      city: "Nagpur",
      state: "Maharashtra",
      source: "walk_in",
      tag_id: "tag-03",
      deal_type: "new_business",
      assigned_to: "u-02",
      status: "follow_up",
      priority: "medium",
      budget: 300000,
      expected_value: 280000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-25",
      last_followup_date: "2026-09-17",
      followup_count: 2,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-11T13:30:00Z",
      sub_requirement: "OPD token display system and digital prescription generator."
    },
    {
      id: "lead-109",
      name: "Pradeep Joshi",
      company_name: "Modern Public Senior School",
      account_id: null,
      phone: "+91 98290 87654",
      email: "admin@modernpublicjaipur.org",
      city: "Jaipur",
      state: "Rajasthan",
      source: "cold_call",
      tag_id: "tag-01",
      deal_type: "new_business",
      assigned_to: null, // Pool
      status: "new",
      priority: "high",
      budget: 450000,
      expected_value: 420000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-23",
      last_followup_date: null,
      followup_count: 0,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-22T09:15:00Z",
      sub_requirement: "In search of integrated ERP with online fee collection before October term."
    },
    {
      id: "lead-110",
      name: "Lakshmi Narayanan",
      company_name: "Kaveri Hospital & Diagnostics",
      account_id: "acc-03",
      phone: "+91 94440 98765",
      email: "ithead@kaverihospital.org",
      city: "Chennai",
      state: "Tamil Nadu",
      source: "referral",
      tag_id: "tag-03",
      deal_type: "upsell",
      assigned_to: "u-02",
      status: "proposal",
      priority: "high",
      budget: 600000,
      expected_value: 550000,
      probability_override: 75, // Override demo
      won_amount: null,
      next_followup_date: "2026-09-22", // Due today!
      last_followup_date: "2026-09-19",
      followup_count: 4,
      brd_url: "/files/brd/lead-110/LabModule_Integration_Scope.pdf",
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-08-20T11:00:00Z",
      sub_requirement: "LIMS barcode machine interface with automated WhatsApp report delivery."
    },
    {
      id: "lead-111",
      name: "Anil Bharadwaj",
      company_name: "Delhi World Public School",
      account_id: null,
      phone: "+91 98490 11223",
      email: "principal@dwpshyderabad.in",
      city: "Hyderabad",
      state: "Telangana",
      source: "website",
      tag_id: "tag-01",
      deal_type: "new_business",
      assigned_to: "u-02",
      status: "new",
      priority: "high",
      budget: 550000,
      expected_value: 500000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-22",
      last_followup_date: null,
      followup_count: 0,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-22T08:30:00Z",
      sub_requirement: "Assigned today at 08:30 AM. Looking for GPS bus tracker and parent mobile app."
    },
    {
      id: "lead-112",
      name: "Pooja Hegde",
      company_name: "Rainbow Kids Kindergarten Network",
      account_id: null,
      phone: "+91 97410 44556",
      email: "admin@rainbowkids.org",
      city: "Bengaluru",
      state: "Karnataka",
      source: "social_media",
      tag_id: "tag-01",
      deal_type: "new_business",
      assigned_to: "u-02",
      status: "new",
      priority: "high",
      budget: 320000,
      expected_value: 300000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-22",
      last_followup_date: null,
      followup_count: 0,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-22T09:10:00Z",
      sub_requirement: "Assigned today at 09:10 AM. Untouched inbound lead for 3 pre-school branches."
    },
    {
      id: "lead-113",
      name: "Sanjay Singhal",
      company_name: "Singhal Diagnostic Labs",
      account_id: null,
      phone: "+91 98220 88990",
      email: "sanjay@singhallabs.com",
      city: "Pune",
      state: "Maharashtra",
      source: "cold_call",
      tag_id: "tag-03",
      deal_type: "new_business",
      assigned_to: "u-02",
      status: "contacted",
      priority: "medium",
      budget: 280000,
      expected_value: 260000,
      probability_override: null,
      won_amount: null,
      next_followup_date: "2026-09-23",
      last_followup_date: "2026-09-22",
      followup_count: 1,
      brd_url: null,
      lost_reason: null,
      invalid_reason: null,
      created_by: "u-01",
      created_at: "2026-09-21T14:00:00Z",
      sub_requirement: "WhatsApp report dispatch automation for 4 collection centers."
    }
  ],

  lead_interactions: [
    {
      id: "int-today-01",
      lead_id: "lead-101",
      bdm_id: "u-02",
      type: "call",
      call_result: "terms_agreed",
      call_result_label: "Terms Agreed / Deal Finalizing",
      call_result_type: "positive", // 'positive', 'neutral', 'negative'
      notes: "Followed up with Dr. Rajeshwar Rao on contract terms. Agreed on ₹4,80,000 for 1,200 students with RFID bus integration.",
      status_snapshot: "proposal",
      next_action: "Send final agreement copy for trustee signatures.",
      created_at: "2026-09-22T09:45:00Z"
    },
    {
      id: "int-today-02",
      lead_id: "lead-102",
      bdm_id: "u-02",
      type: "whatsapp",
      call_result: "demo_scheduled",
      call_result_label: "Demo Video Sent / Follow-up Set",
      call_result_type: "positive",
      notes: "Sent UI demo video of driver dispatch app to Vikram Singhania. Addressed offline GPS sync query.",
      status_snapshot: "follow_up",
      next_action: "Call at 4:30 PM for architecture review.",
      created_at: "2026-09-22T10:30:00Z"
    },
    {
      id: "int-today-03",
      lead_id: "lead-110",
      bdm_id: "u-02",
      type: "meeting",
      call_result: "demo_completed",
      call_result_label: "Demo Completed / Highly Interested",
      call_result_type: "positive",
      notes: "Conducted virtual Zoom demo with Kaveri Hospital IT Head on Mindray analyzer integration.",
      status_snapshot: "proposal",
      next_action: "Provide revised timeline estimate.",
      created_at: "2026-09-22T11:15:00Z"
    },
    {
      id: "int-today-04",
      lead_id: "lead-108",
      bdm_id: "u-02",
      type: "call",
      call_result: "site_visit",
      call_result_label: "Site Visit Scheduled",
      call_result_type: "positive",
      notes: "Called Dr. Suniti Deshmukh to confirm clinic OPD token display requirement.",
      status_snapshot: "follow_up",
      next_action: "Schedule physical site survey on Thursday.",
      created_at: "2026-09-22T14:20:00Z"
    },
    {
      id: "int-today-05",
      lead_id: "lead-111",
      bdm_id: "u-02",
      type: "call",
      call_result: "no_answer",
      call_result_label: "Ringing / No Answer",
      call_result_type: "neutral",
      notes: "Called Anil Bharadwaj (Delhi World Public School). Phone rang continuously without response. Sent introductory WhatsApp brochure.",
      status_snapshot: "new",
      next_action: "Retry call today at 04:30 PM.",
      created_at: "2026-09-22T15:10:00Z"
    },
    {
      id: "int-today-06",
      lead_id: "lead-113",
      bdm_id: "u-02",
      type: "call",
      call_result: "interested",
      call_result_label: "Interested / Call Back Set",
      call_result_type: "positive",
      notes: "Spoke with Sanjay Singhal. Very interested in WhatsApp report delivery module. Requested callback tomorrow when head pathologist is in office.",
      status_snapshot: "contacted",
      next_action: "Call Wednesday 10:30 AM.",
      created_at: "2026-09-22T16:05:00Z"
    },
    {
      id: "int-01",
      lead_id: "lead-101",
      bdm_id: "u-02",
      type: "meeting",
      notes: "Met with Dr. Rao and the school IT committee. Demonstrated the student attendance & fee collection module. Committee was impressed with bus tracking RFID.",
      status_snapshot: "proposal",
      next_action: "Send revised proposal with 3-year AMC terms.",
      created_at: "2026-09-18T16:30:00Z"
    },
    {
      id: "int-02",
      lead_id: "lead-101",
      bdm_id: "u-02",
      type: "call",
      notes: "Followed up on commercial terms. Trust agreed to ₹4,80,000 subject to onboarding training for 40 teachers.",
      status_snapshot: "proposal",
      next_action: "Final contract signing call scheduled for today.",
      created_at: "2026-09-15T11:15:00Z"
    },
    {
      id: "int-03",
      lead_id: "lead-102",
      bdm_id: "u-02",
      type: "whatsapp",
      notes: "Shared the UI mockup link for the driver dispatch application. Client asked about offline GPS ping caching.",
      status_snapshot: "follow_up",
      next_action: "Confirm technical architecture with development team.",
      created_at: "2026-09-15T14:00:00Z"
    },
    {
      id: "int-04",
      lead_id: "lead-103",
      bdm_id: "u-03",
      type: "call",
      notes: "Introductory telecall. Principal requested an informational brochure and fee calculator sheet.",
      status_snapshot: "contacted",
      next_action: "Send brochure via email and schedule remote Zoom demo.",
      created_at: "2026-09-19T10:30:00Z"
    },
    {
      id: "int-05",
      lead_id: "lead-110",
      bdm_id: "u-02",
      type: "site_visit",
      call_result: "demo_completed",
      call_result_label: "Site Inspection Completed",
      call_result_type: "positive",
      notes: "Visited Kaveri Hospital lab department in Chennai. Verified Mindray biochemistry analyzer RS232 output ports.",
      status_snapshot: "proposal",
      next_action: "Submit quote for HL7 integration driver.",
      created_at: "2026-09-19T17:45:00Z"
    },
    {
      id: "int-108-01",
      lead_id: "lead-108",
      bdm_id: "u-02",
      type: "call",
      call_result: "interested",
      call_result_label: "Initial Discovery / High Interest",
      call_result_type: "positive",
      notes: "Introductory discovery call with Dr. Suniti Deshmukh. Clinic currently handles 140+ OPD patients daily on paper tokens causing waiting room congestion. Interested in smart LED token display with patient SMS alerts.",
      status_snapshot: "contacted",
      next_action: "Send product spec brochure and pricing sheet for 2-consulting-room clinic setup.",
      created_at: "2026-09-12T11:00:00Z"
    },
    {
      id: "int-108-02",
      lead_id: "lead-108",
      bdm_id: "u-02",
      type: "whatsapp",
      call_result: "demo_scheduled",
      call_result_label: "Spec & Demo Video Shared",
      call_result_type: "positive",
      notes: "Shared Hospital ERP token management video walkthrough and hardware specifications over WhatsApp. Doctor reviewed and requested on-site survey to check counter placement.",
      status_snapshot: "follow_up",
      next_action: "Follow up to schedule physical counter layout survey.",
      created_at: "2026-09-17T15:30:00Z"
    },
    {
      id: "int-105-01",
      lead_id: "lead-105",
      bdm_id: "u-02",
      type: "meeting",
      call_result: "terms_agreed",
      call_result_label: "Trust Approval / Contract Signed",
      call_result_type: "positive",
      notes: "Final contract signing with Father Thomas Mathew and Delhi Public Academy Trust board. Agreed on ₹4,50,000 for 1,800 students complete ERP license.",
      status_snapshot: "won",
      next_action: "Handover to deployment & training engineering team.",
      created_at: "2026-09-14T16:00:00Z"
    }
  ],

  lead_status_history: [
    { id: "sh-01", lead_id: "lead-101", old_status: "new", new_status: "contacted", changed_by: "u-02", changed_at: "2026-09-04T11:00:00Z" },
    { id: "sh-02", lead_id: "lead-101", old_status: "contacted", new_status: "follow_up", changed_by: "u-02", changed_at: "2026-09-08T15:20:00Z" },
    { id: "sh-03", lead_id: "lead-101", old_status: "follow_up", new_status: "proposal", changed_by: "u-02", changed_at: "2026-09-15T12:00:00Z" },
    { id: "sh-04", lead_id: "lead-105", old_status: "proposal", new_status: "won", changed_by: "u-02", changed_at: "2026-09-14T16:00:00Z" },
    { id: "sh-05", lead_id: "lead-106", old_status: "contacted", new_status: "lost", changed_by: "u-04", changed_at: "2026-09-12T14:30:00Z" },
    { id: "sh-06", lead_id: "lead-107", old_status: "new", new_status: "invalid", changed_by: "u-03", changed_at: "2026-09-16T15:15:00Z" }
  ],

  lead_assignment_history: [
    { id: "ah-01", lead_id: "lead-101", assigned_from: null, assigned_to: "u-02", assigned_by: "u-01", assigned_at: "2026-09-02T10:30:00Z" },
    { id: "ah-02", lead_id: "lead-102", assigned_from: null, assigned_to: "u-02", assigned_by: "u-01", assigned_at: "2026-09-05T14:30:00Z" },
    { id: "ah-03", lead_id: "lead-103", assigned_from: null, assigned_to: "u-03", assigned_by: "u-01", assigned_at: "2026-09-10T11:15:00Z" },
    { id: "ah-04", lead_id: "lead-104", assigned_from: null, assigned_to: "u-04", assigned_by: "u-01", assigned_at: "2026-09-21T17:00:00Z" },
    { id: "ah-05", lead_id: "lead-110", assigned_from: null, assigned_to: "u-02", assigned_by: "u-01", assigned_at: "2026-08-20T11:15:00Z" }
  ],

  attendance: [
    // Today (2026-09-22)
    { id: "att-01", bdm_id: "u-02", date: "2026-09-22", check_in_time: "2026-09-22T09:28:14Z", check_out_time: null, status: "present", edited_by: null, edited_at: null },
    { id: "att-02", bdm_id: "u-03", date: "2026-09-22", check_in_time: "2026-09-22T09:45:00Z", check_out_time: null, status: "present", edited_by: null, edited_at: null },
    { id: "att-03", bdm_id: "u-04", date: "2026-09-22", check_in_time: null, check_out_time: null, status: "leave", edited_by: "u-01", edited_at: "2026-09-22T08:30:00Z" },
    { id: "att-04", bdm_id: "u-05", date: "2026-09-22", check_in_time: "2026-09-22T10:05:00Z", check_out_time: null, status: "half_day", edited_by: null, edited_at: null },
    // Yesterday (2026-09-21)
    { id: "att-05", bdm_id: "u-02", date: "2026-09-21", check_in_time: "2026-09-21T09:30:00Z", check_out_time: "2026-09-21T18:45:00Z", status: "present", edited_by: null, edited_at: null },
    { id: "att-06", bdm_id: "u-03", date: "2026-09-21", check_in_time: "2026-09-21T09:20:00Z", check_out_time: "2026-09-21T18:30:00Z", status: "present", edited_by: null, edited_at: null },
    { id: "att-07", bdm_id: "u-04", date: "2026-09-21", check_in_time: "2026-09-21T09:55:00Z", check_out_time: "2026-09-21T18:15:00Z", status: "present", edited_by: null, edited_at: null },
    { id: "att-08", bdm_id: "u-05", date: "2026-09-21", check_in_time: null, check_out_time: null, status: "absent", edited_by: null, edited_at: null }
  ],

  holidays: [
    { id: "hol-01", date: "2026-01-26", name: "Republic Day" },
    { id: "hol-02", date: "2026-03-04", name: "Holi" },
    { id: "hol-03", date: "2026-08-15", name: "Independence Day" },
    { id: "hol-04", date: "2026-10-02", name: "Gandhi Jayanti" },
    { id: "hol-05", date: "2026-10-20", name: "Dussehra" },
    { id: "hol-06", date: "2026-11-08", name: "Diwali" },
    { id: "hol-07", date: "2026-12-25", name: "Christmas" }
  ],

  notifications: [
    {
      id: "notif-01",
      user_id: "u-02",
      lead_id: "lead-101",
      type: "followup_due",
      message: "Follow-up due today with Dr. Rajeshwar Rao (Heritage Valley Int'l School)",
      is_read: false,
      created_at: "2026-09-22T03:30:00Z"
    },
    {
      id: "notif-02",
      user_id: "u-02",
      lead_id: "lead-102",
      type: "followup_overdue",
      message: "OVERDUE: Follow-up was due yesterday with Vikram Singhania (Apex Logistics)",
      is_read: false,
      created_at: "2026-09-22T03:30:00Z"
    },
    {
      id: "notif-03",
      user_id: "u-02",
      lead_id: "lead-110",
      type: "lead_assigned",
      message: "New lead assigned to you: Lakshmi Narayanan (Kaveri Hospital Lab Module)",
      is_read: true,
      created_at: "2026-09-20T05:45:00Z"
    },
    {
      id: "notif-04",
      user_id: "u-01",
      lead_id: "lead-105",
      type: "other",
      message: "Lead Won! Aarav Sharma marked Delhi Public Academy Phase 2 won for ₹4,50,000",
      is_read: false,
      created_at: "2026-09-14T16:00:00Z"
    }
  ]
};

// Default stage probabilities per PRD
const STAGE_PROBABILITIES = {
  new: 10,
  contacted: 20,
  follow_up: 40,
  proposal: 60,
  negotiation: 60, // backward compat alias
  won: 100,
  lost: 0,
  invalid: 0
};
